# Grade Headnotes

We are given a zipped folder of 7k Indian Supreme Court court judgements and their headnotes/summaries. We have created a rubric to analyze the headnotes and grade them. We will perform in-context learning by prompting Meta's Llama 3.1 8B model (4-bit quantized) with the rubric and few-shot examples. We want the model to grade the headnotes and provide an explanation for each grade assigned. We will then output everything into a CSV file that we can use for further work.

## Config and Imports

In [ ]:
%pip install bitsandbytes

Collecting bitsandbytes
  Downloading bitsandbytes-0.45.5-py3-none-manylinux_2_24_x86_64.whl.metadata (5.0 kB)
Requirement already satisfied: torch<3,>=2.0 in /usr/local/lib/python3.11/dist-packages (from bitsandbytes) (2.6.0+cu124)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from bitsandbytes) (2.0.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (4.13.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (2025.3.2)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch<3,>=2.0->bitsandbytes)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch<3,>=2.0->bitsandbytes)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch<3,>=2.0->bitsandbytes)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch<3,>=2.0->bitsandbytes)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch<3,>=2.0->bitsandbytes)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch<3,>=2.0->bitsandbytes)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch<3,>=2.0->bitsandbytes)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch<3,>=2.0->bitsandbytes)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch<3,>=2.0->bitsandbytes)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch<3,>=2.0->bitsandbytes)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch<3,>=2.0->bitsandbytes) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch<3,>=2.0->bitsandbytes) (3.0.2)
Downloading bitsandbytes-0.45.5-py3-none-manylinux_2_24_x86_64.whl (76.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.1/76.1 MB 26.6 MB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 2.3 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 73.0 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 92.3 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 54.5 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.5 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 9.6 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 37.5 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 16.8 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 2.7 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 104.9 MB/s eta 0:00:00
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, bitsandbytes
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
Successfully installed bitsandbytes-0.45.5 nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127

In [ ]:
from huggingface_hub import login
from google.colab import userdata
from tqdm.auto import tqdm
from transformers import BitsAndBytesConfig, pipeline
import csv
import os
import pandas as pd
import torch

In [3]:
MODEL_NAME = "meta-llama/Meta-Llama-3.1-8B-Instruct"

In [4]:
rubric_prompt = """
You are a professor at a law school and are in charge of grading headnotes/summaries students have written for court judgements.
Case judgments represent rulings issued by judges in judicial proceedings, often comprising extensive transcripts spanning dozens of pages.
An excellent headnote captures the core of the judgment properly, succinctly, and completely.
Your job is to fairly judge the written headnotes, so be as strict as possible.

This is the rubric:
- PAST TENSE: The headnote is written in the past tense.
- METADATA: The headnote includes the case name, judgement number, court, judge(s), and date of judgement.
- INTRODUCTION: The headnote introduction describes the field of law that the case deals with, and does not directly jump into the case details.
- KEY FACTS: The headnote includes who filed the case, why the case was filed, and what remedy the filer wants.
- KEY ARGUMENTS: The headnote includes both sides' submissions and reasons to support their position.
- RELEVANT LAWS: The headnote references relevant legislation and concepts to support the case judgement.
- CONCLUSION: The headnote includes the case's conclusion and procedural disposition (ex: permitted, dismissed, reversed, remanded, affirmed, etc.).

Your job is to read the judgement and headnote provided, then go through the rubric items one by one.
Mark each rubric item as TRUE or FALSE.
Output each rubric item and what you assigned it.
Do not introduce any other rubric items.
Do not output anything else except for the 8 bullet points corresponding to rubric items - no more, no less.
Your output should be final, and no more changes can be made.

Format of your output:
- PAST TENSE: TRUE/FALSE
- METADATA: TRUE/FALSE
- INTRODUCTION: TRUE/FALSE
- KEY FACTS: TRUE/FALSE
- KEY ARGUMENTS: TRUE/FALSE
- RELEVANT LAWS: TRUE/FALSE
- CONCLUSION: TRUE/FALSE
"""

## Import the Dataset

In [5]:
!unzip original_data.zip

Streaming output truncated to the last 5000 lines.
  inflating: original_data/train_data/summary/63.txt
  inflating: original_data/train_data/summary/6400.txt
  inflating: original_data/train_data/summary/5109.txt
  inflating: original_data/train_data/summary/2666.txt
  inflating: original_data/train_data/summary/3578.txt
  inflating: original_data/train_data/summary/4217.txt
  inflating: original_data/train_data/summary/2672.txt
  inflating: original_data/train_data/summary/4203.txt
  inflating: original_data/train_data/summary/837.txt
  inflating: original_data/train_data/summary/6414.txt
  inflating: original_data/train_data/summary/77.txt
  inflating: original_data/train_data/summary/6372.txt
  inflating: original_data/train_data/summary/189.txt
  inflating: original_data/train_data/summary/4565.txt
  inflating: original_data/train_data/summary/2114.txt
  inflating: original_data/train_data/summary/1435.txt
  inflating: original_data/train_data/summary/7044.txt
  inflating: original_data/train_data/summary/3222.txt
  inflating: original_data/train_data/summary/5653.txt
  inflating: original_data/train_data/summary/5135.txt
  inflating: original_data/train_data/summary/3544.txt
  inflating: original_data/train_data/summary/2882.txt
  inflating: original_data/train_data/summary/1353.txt
  inflating: original_data/train_data/summary/1347.txt
  inflating: original_data/train_data/summary/6428.txt
  inflating: original_data/train_data/summary/5121.txt
  inflating: original_data/train_data/summary/3550.txt
  inflating: original_data/train_data/summary/2896.txt
  inflating: original_data/train_data/summary/4559.txt
  inflating: original_data/train_data/summary/3236.txt
  inflating: original_data/train_data/summary/2128.txt
  inflating: original_data/train_data/summary/5647.txt
  inflating: original_data/train_data/summary/1421.txt
  inflating: original_data/train_data/summary/7050.txt
  inflating: original_data/train_data/summary/5900.txt
  inflating: original_data/train_data/summary/2909.txt
  inflating: original_data/train_data/summary/994.txt
  inflating: original_data/train_data/summary/980.txt
  inflating: original_data/train_data/summary/758.txt
  inflating: original_data/train_data/summary/5914.txt
  inflating: original_data/train_data/summary/3395.txt
  inflating: original_data/train_data/summary/1582.txt
  inflating: original_data/train_data/summary/770.txt
  inflating: original_data/train_data/summary/5082.txt
  inflating: original_data/train_data/summary/2935.txt
  inflating: original_data/train_data/summary/5096.txt
  inflating: original_data/train_data/summary/2921.txt
  inflating: original_data/train_data/summary/4388.txt
  inflating: original_data/train_data/summary/764.txt
  inflating: original_data/train_data/summary/1596.txt
  inflating: original_data/train_data/summary/3381.txt
  inflating: original_data/train_data/summary/5928.txt
  inflating: original_data/train_data/summary/2074.txt
  inflating: original_data/train_data/summary/4405.txt
  inflating: original_data/train_data/summary/6212.txt
  inflating: original_data/train_data/summary/6574.txt
  inflating: original_data/train_data/summary/957.txt
  inflating: original_data/train_data/summary/4363.txt
  inflating: original_data/train_data/summary/2712.txt
  inflating: original_data/train_data/summary/4377.txt
  inflating: original_data/train_data/summary/3418.txt
  inflating: original_data/train_data/summary/2706.txt
  inflating: original_data/train_data/summary/5069.txt
  inflating: original_data/train_data/summary/6560.txt
  inflating: original_data/train_data/summary/943.txt
  inflating: original_data/train_data/summary/7118.txt
  inflating: original_data/train_data/summary/1569.txt
  inflating: original_data/train_data/summary/6206.txt
  inflating: original_data/train_data/summary/2060.txt
  inflating: original_data/train_data/summary/4411.txt
  inflating: original_data/train_data/summary/1541.txt
  inflating: original_data/train_data/summary/5727.txt
  inflating: original_data/train_data/summary/2048.txt
  inflating: original_data/train_data/summary/4439.txt
  inflating: original_data/train_data/summary/3430.txt
  inflating: original_data/train_data/summary/5041.txt
  inflating: original_data/train_data/summary/6548.txt
  inflating: original_data/train_data/summary/1227.txt
  inflating: original_data/train_data/summary/1233.txt
  inflating: original_data/train_data/summary/3424.txt
  inflating: original_data/train_data/summary/5055.txt
  inflating: original_data/train_data/summary/5733.txt
  inflating: original_data/train_data/summary/3342.txt
  inflating: original_data/train_data/summary/7124.txt
  inflating: original_data/train_data/summary/1555.txt
  inflating: original_data/train_data/summary/3815.txt
  inflating: original_data/train_data/summary/1964.txt
  inflating: original_data/train_data/summary/228.txt
  inflating: original_data/train_data/summary/1970.txt
  inflating: original_data/train_data/summary/4808.txt
  inflating: original_data/train_data/summary/3801.txt
  inflating: original_data/train_data/summary/6979.txt
  inflating: original_data/train_data/summary/5280.txt
  inflating: original_data/train_data/summary/3829.txt
  inflating: original_data/train_data/summary/572.txt
  inflating: original_data/train_data/summary/6789.txt
  inflating: original_data/train_data/summary/6951.txt
  inflating: original_data/train_data/summary/1958.txt
  inflating: original_data/train_data/summary/214.txt
  inflating: original_data/train_data/summary/1780.txt
  inflating: original_data/train_data/summary/4820.txt
  inflating: original_data/train_data/summary/2289.txt
  inflating: original_data/train_data/summary/3197.txt
  inflating: original_data/train_data/summary/4834.txt
  inflating: original_data/train_data/summary/3183.txt
  inflating: original_data/train_data/summary/1794.txt
  inflating: original_data/train_data/summary/200.txt
  inflating: original_data/train_data/summary/566.txt
  inflating: original_data/train_data/summary/6945.txt
  inflating: original_data/train_data/summary/5294.txt
  inflating: original_data/train_data/summary/2510.txt
  inflating: original_data/train_data/summary/4161.txt
  inflating: original_data/train_data/summary/1019.txt
  inflating: original_data/train_data/summary/6776.txt
  inflating: original_data/train_data/summary/6010.txt
  inflating: original_data/train_data/summary/4607.txt
  inflating: original_data/train_data/summary/2276.txt
  inflating: original_data/train_data/summary/5519.txt
  inflating: original_data/train_data/summary/4613.txt
  inflating: original_data/train_data/summary/2262.txt
  inflating: original_data/train_data/summary/6004.txt
  inflating: original_data/train_data/summary/599.txt
  inflating: original_data/train_data/summary/6762.txt
  inflating: original_data/train_data/summary/2504.txt
  inflating: original_data/train_data/summary/4175.txt
  inflating: original_data/train_data/summary/6992.txt
  inflating: original_data/train_data/summary/1025.txt
  inflating: original_data/train_data/summary/5243.txt
  inflating: original_data/train_data/summary/3632.txt
  inflating: original_data/train_data/summary/3154.txt
  inflating: original_data/train_data/summary/5525.txt
  inflating: original_data/train_data/summary/1743.txt
  inflating: original_data/train_data/summary/6038.txt
  inflating: original_data/train_data/summary/1757.txt
  inflating: original_data/train_data/summary/3140.txt
  inflating: original_data/train_data/summary/5531.txt
  inflating: original_data/train_data/summary/5257.txt
  inflating: original_data/train_data/summary/2538.txt
  inflating: original_data/train_data/summary/3626.txt
  inflating: original_data/train_data/summary/4149.txt
  inflating: original_data/train_data/summary/6986.txt
  inflating: original_data/train_data/summary/1031.txt
  inflating: original_data/train_data/summary/1999.txt
  inflating: original_data/train_data/summary/1741.txt
  inflating: original_data/train_data/summary/5527.txt
  inflating: original_data/train_data/summary/3156.txt
  inflating: original_data/train_data/summary/4639.txt
  inflating: original_data/train_data/summary/3630.txt
  inflating: original_data/train_data/summary/5241.txt
  inflating: original_data/train_data/summary/6748.txt
  inflating: original_data/train_data/summary/1027.txt
  inflating: original_data/train_data/summary/6990.txt
  inflating: original_data/train_data/summary/1033.txt
  inflating: original_data/train_data/summary/6984.txt
  inflating: original_data/train_data/summary/3624.txt
  inflating: original_data/train_data/summary/5255.txt
  inflating: original_data/train_data/summary/5533.txt
  inflating: original_data/train_data/summary/3142.txt
  inflating: original_data/train_data/summary/1755.txt
  inflating: original_data/train_data/summary/2274.txt
  inflating: original_data/train_data/summary/4605.txt
  inflating: original_data/train_data/summary/6012.txt
  inflating: original_data/train_data/summary/6774.txt
  inflating: original_data/train_data/summary/4163.txt
  inflating: original_data/train_data/summary/2512.txt
  inflating: original_data/train_data/summary/4177.txt
  inflating: original_data/train_data/summary/3618.txt
  inflating: original_data/train_data/summary/2506.txt
  inflating: original_data/train_data/summary/5269.txt
  inflating: original_data/train_data/summary/6760.txt
  inflating: original_data/train_data/summary/1769.txt
  inflating: original_data/train_data/summary/6006.txt
  inflating: original_data/train_data/summary/2260.txt
  inflating: original_data/train_data/summary/4611.txt
  inflating: original_data/train_data/summary/3195.txt
  inflating: original_data/train_data/summary/4822.txt
  inflating: original_data/train_data/summary/1782.txt
  inflating: original_data/train_data/summary/216.txt
  inflating: original_data/train_data/summary/6953.txt
  inflating: original_data/train_data/summary/570.txt
  inflating: original_data/train_data/summary/5282.txt
  inflating: original_data/train_data/summary/5296.txt
  inflating: original_data/train_data/summary/4188.txt
  inflating: original_data/train_data/summary/6947.txt
  inflating: original_data/train_data/summary/564.txt
  inflating: original_data/train_data/summary/202.txt
  inflating: original_data/train_data/summary/1796.txt
  inflating: original_data/train_data/summary/3181.txt
  inflating: original_data/train_data/summary/4836.txt
  inflating: original_data/train_data/summary/1966.txt
  inflating: original_data/train_data/summary/3817.txt
  inflating: original_data/train_data/summary/558.txt
  inflating: original_data/train_data/summary/3803.txt
  inflating: original_data/train_data/summary/1972.txt
  inflating: original_data/train_data/summary/969.txt
  inflating: original_data/train_data/summary/1225.txt
  inflating: original_data/train_data/summary/5043.txt
  inflating: original_data/train_data/summary/3432.txt
  inflating: original_data/train_data/summary/3354.txt
  inflating: original_data/train_data/summary/5725.txt
  inflating: original_data/train_data/summary/1543.txt
  inflating: original_data/train_data/summary/7132.txt
  inflating: original_data/train_data/summary/6238.txt
  inflating: original_data/train_data/summary/1557.txt
  inflating: original_data/train_data/summary/7126.txt
  inflating: original_data/train_data/summary/3340.txt
  inflating: original_data/train_data/summary/5731.txt
  inflating: original_data/train_data/summary/5057.txt
  inflating: original_data/train_data/summary/2738.txt
  inflating: original_data/train_data/summary/3426.txt
  inflating: original_data/train_data/summary/4349.txt
  inflating: original_data/train_data/summary/1231.txt
  inflating: original_data/train_data/summary/2710.txt
  inflating: original_data/train_data/summary/4361.txt
  inflating: original_data/train_data/summary/955.txt
  inflating: original_data/train_data/summary/1219.txt
  inflating: original_data/train_data/summary/6576.txt
  inflating: original_data/train_data/summary/6210.txt
  inflating: original_data/train_data/summary/4407.txt
  inflating: original_data/train_data/summary/3368.txt
  inflating: original_data/train_data/summary/2076.txt
  inflating: original_data/train_data/summary/5719.txt
  inflating: original_data/train_data/summary/4413.txt
  inflating: original_data/train_data/summary/2062.txt
  inflating: original_data/train_data/summary/6204.txt
  inflating: original_data/train_data/summary/941.txt
  inflating: original_data/train_data/summary/799.txt
  inflating: original_data/train_data/summary/6562.txt
  inflating: original_data/train_data/summary/2704.txt
  inflating: original_data/train_data/summary/4375.txt
  inflating: original_data/train_data/summary/2937.txt
  inflating: original_data/train_data/summary/5080.txt
  inflating: original_data/train_data/summary/772.txt
  inflating: original_data/train_data/summary/6589.txt
  inflating: original_data/train_data/summary/1580.txt
  inflating: original_data/train_data/summary/2089.txt
  inflating: original_data/train_data/summary/3397.txt
  inflating: original_data/train_data/summary/3383.txt
  inflating: original_data/train_data/summary/1594.txt
  inflating: original_data/train_data/summary/766.txt
  inflating: original_data/train_data/summary/2923.txt
  inflating: original_data/train_data/summary/5094.txt
  inflating: original_data/train_data/summary/996.txt
  inflating: original_data/train_data/summary/5902.txt
  inflating: original_data/train_data/summary/5916.txt
  inflating: original_data/train_data/summary/982.txt
  inflating: original_data/train_data/summary/1351.txt
  inflating: original_data/train_data/summary/2880.txt
  inflating: original_data/train_data/summary/4229.txt
  inflating: original_data/train_data/summary/3546.txt
  inflating: original_data/train_data/summary/2658.txt
  inflating: original_data/train_data/summary/5137.txt
  inflating: original_data/train_data/summary/5651.txt
  inflating: original_data/train_data/summary/3220.txt
  inflating: original_data/train_data/summary/5889.txt
  inflating: original_data/train_data/summary/7046.txt
  inflating: original_data/train_data/summary/1437.txt
  inflating: original_data/train_data/summary/6358.txt
  inflating: original_data/train_data/summary/7052.txt
  inflating: original_data/train_data/summary/1423.txt
  inflating: original_data/train_data/summary/5645.txt
  inflating: original_data/train_data/summary/3234.txt
  inflating: original_data/train_data/summary/2894.txt
  inflating: original_data/train_data/summary/3552.txt
  inflating: original_data/train_data/summary/5123.txt
  inflating: original_data/train_data/summary/49.txt
  inflating: original_data/train_data/summary/1345.txt
  inflating: original_data/train_data/summary/809.txt
  inflating: original_data/train_data/summary/4215.txt
  inflating: original_data/train_data/summary/2664.txt
  inflating: original_data/train_data/summary/6402.txt
  inflating: original_data/train_data/summary/61.txt
  inflating: original_data/train_data/summary/821.txt
  inflating: original_data/train_data/summary/6364.txt
  inflating: original_data/train_data/summary/2102.txt
  inflating: original_data/train_data/summary/4573.txt
  inflating: original_data/train_data/summary/5679.txt
  inflating: original_data/train_data/summary/2116.txt
  inflating: original_data/train_data/summary/3208.txt
  inflating: original_data/train_data/summary/4567.txt
  inflating: original_data/train_data/summary/6370.txt
  inflating: original_data/train_data/summary/75.txt
  inflating: original_data/train_data/summary/6416.txt
  inflating: original_data/train_data/summary/1379.txt
  inflating: original_data/train_data/summary/835.txt
  inflating: original_data/train_data/summary/4201.txt
  inflating: original_data/train_data/summary/2670.txt
  inflating: original_data/train_data/summary/2843.txt
  inflating: original_data/train_data/summary/3585.txt
  inflating: original_data/train_data/summary/606.txt
  inflating: original_data/train_data/summary/1392.txt
  inflating: original_data/train_data/summary/160.txt
  inflating: original_data/train_data/summary/7085.txt
  inflating: original_data/train_data/summary/5692.txt
  inflating: original_data/train_data/summary/4598.txt
  inflating: original_data/train_data/summary/5686.txt
  inflating: original_data/train_data/summary/174.txt
  inflating: original_data/train_data/summary/7091.txt
  inflating: original_data/train_data/summary/1386.txt
  inflating: original_data/train_data/summary/612.txt
  inflating: original_data/train_data/summary/2857.txt
  inflating: original_data/train_data/summary/3591.txt
  inflating: original_data/train_data/summary/5876.txt
  inflating: original_data/train_data/summary/148.txt
  inflating: original_data/train_data/summary/5862.txt
  inflating: original_data/train_data/summary/1635.txt
  inflating: original_data/train_data/summary/3022.txt
  inflating: original_data/train_data/summary/4995.txt
  inflating: original_data/train_data/summary/5453.txt
  inflating: original_data/train_data/summary/5335.txt
  inflating: original_data/train_data/summary/3744.txt
  inflating: original_data/train_data/summary/1153.txt
  inflating: original_data/train_data/summary/1147.txt
  inflating: original_data/train_data/summary/6628.txt
  inflating: original_data/train_data/summary/5321.txt
  inflating: original_data/train_data/summary/3988.txt
  inflating: original_data/train_data/summary/3750.txt
  inflating: original_data/train_data/summary/4759.txt
  inflating: original_data/train_data/summary/3036.txt
  inflating: original_data/train_data/summary/4981.txt
  inflating: original_data/train_data/summary/2328.txt
  inflating: original_data/train_data/summary/5447.txt
  inflating: original_data/train_data/summary/1621.txt
  inflating: original_data/train_data/summary/4771.txt
  inflating: original_data/train_data/summary/2300.txt
  inflating: original_data/train_data/summary/6166.txt
  inflating: original_data/train_data/summary/1609.txt
  inflating: original_data/train_data/summary/6600.txt
  inflating: original_data/train_data/summary/5309.txt
  inflating: original_data/train_data/summary/2466.txt
  inflating: original_data/train_data/summary/3778.txt
  inflating: original_data/train_data/summary/4017.txt
  inflating: original_data/train_data/summary/2472.txt
  inflating: original_data/train_data/summary/4003.txt
  inflating: original_data/train_data/summary/6614.txt
  inflating: original_data/train_data/summary/6172.txt
  inflating: original_data/train_data/summary/389.txt
  inflating: original_data/train_data/summary/4765.txt
  inflating: original_data/train_data/summary/2314.txt
  inflating: original_data/train_data/summary/4956.txt
  inflating: original_data/train_data/summary/5490.txt
  inflating: original_data/train_data/summary/6199.txt
  inflating: original_data/train_data/summary/1190.txt
  inflating: original_data/train_data/summary/404.txt
  inflating: original_data/train_data/summary/6827.txt
  inflating: original_data/train_data/summary/3787.txt
  inflating: original_data/train_data/summary/2499.txt
  inflating: original_data/train_data/summary/3793.txt
  inflating: original_data/train_data/summary/410.txt
  inflating: original_data/train_data/summary/1184.txt
  inflating: original_data/train_data/summary/6833.txt
  inflating: original_data/train_data/summary/376.txt
  inflating: original_data/train_data/summary/4942.txt
  inflating: original_data/train_data/summary/5484.txt
  inflating: original_data/train_data/summary/1812.txt
  inflating: original_data/train_data/summary/3963.txt
  inflating: original_data/train_data/summary/438.txt
  inflating: original_data/train_data/summary/3977.txt
  inflating: original_data/train_data/summary/1806.txt
  inflating: original_data/train_data/summary/3976.txt
  inflating: original_data/train_data/summary/1807.txt
  inflating: original_data/train_data/summary/1813.txt
  inflating: original_data/train_data/summary/439.txt

In [6]:
def open_file(path):
    with open(path, 'r') as file:
        return file.read()

In [7]:
content = []
for path in os.listdir('original_data'):
  if not path.endswith('data'):
      continue
  for file_name in os.listdir(f'original_data/{path}/judgement'):
    if not file_name.endswith('.txt'):
      continue
    judgement = open_file(f'original_data/{path}/judgement/{file_name}')
    headnote = open_file(f'original_data/{path}/summary/{file_name}')
    content.append({'judgement': judgement, 'headnote': headnote})

In [8]:
original_df = pd.DataFrame(content)
original_df.head(5)

,judgement,headnote
0,ition (Criminal) No 359 of 1989.\n(Under Artic...,Mr. Kubic Dariusz a Polish national was arrest...
1,: Civil Appeal No. 3373 of 1979.\nFrom the Jud...,This is defendants ' appeal arising out of a s...
2,Civil Appeal No. 571 of 1975 Appeal by Special...,The appellant was appointed on probation as th...
3,RISDICTION: Criminal Appeal No. 47 of 1992.\nF...,With a view to check transportation of illicit...
4,Appeal No. 2847 of 1993.\nFrom the Judgment an...,The appellant had applied for recruitment as E...

In [9]:
original_df.dropna(inplace=True)
original_df.drop_duplicates(subset=['headnote'], inplace=True)
original_df['headnote'] = original_df['headnote'].str.strip()
original_df['judgement'] = original_df['judgement'].str.strip()
original_df.describe()

,judgement,headnote
count,7100,7100
unique,7100,7100
top,ivil Appeals Nos.\n4582 4585 of 1989.\n125 Fro...,The Uttar Pradesh Public Service Commission co...
freq,1,1

## Load the Model

In [10]:
login(userdata.get('HF_TOKEN'))

In [11]:
pipe = pipeline(
    "text-generation",
    model=MODEL_NAME,
    device_map="auto",
    torch_dtype=torch.bfloat16,
    return_full_text=False,
    model_kwargs={
        "quantization_config": BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_compute_dtype=torch.bfloat16)
    }
)

config.json:   0%|          | 0.00/855 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/23.9k [00:00<?, ?B/s]

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

model-00003-of-00004.safetensors:   0%|          | 0.00/4.92G [00:00<?, ?B/s]

model-00001-of-00004.safetensors:   0%|          | 0.00/4.98G [00:00<?, ?B/s]

model-00002-of-00004.safetensors:   0%|          | 0.00/5.00G [00:00<?, ?B/s]

model-00004-of-00004.safetensors:   0%|          | 0.00/1.17G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/184 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/55.4k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.09M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

Device set to use cuda:0

## Go through all the judgements

In [12]:
def append_to_csv(judgement, headnote, response, clean_response):
    with open("judgements_and_graded_headnotes.csv", 'a') as file:
        writer = csv.writer(file)
        writer.writerow([judgement, headnote, response, clean_response])

In [17]:
def clean_response(headnote, response_string):
  response_string = response_string.lower()
  overall_count = 0

  for rubric_item in ["past tense", "metadata", "introduction", "key facts", "key arguments", "relevant laws", "conclusion"]:
    rubric_counts = dict()
    for condition in ["true", "false"]:
      rubric_counts[f'{rubric_item} {condition}'] = response_string.count(f'{rubric_item}: {condition}')

    # sometimes Llama 3 tends to repeat itself to maximize the new token count
    if rubric_counts[f'{rubric_item} true'] > rubric_counts[f'{rubric_item} false']:
      overall_count += 1

  word_count = len(headnote.split(' '))
  if overall_count == 0:
    return 'INVALID RESPONSE'
  elif word_count >= 300 and word_count <= 800:
    overall_count += 1

  if overall_count > 6:
    return 'EXCELLENT'
  elif overall_count > 3:
    return 'MEDIUM'
  else:
    return 'POOR'

In [18]:
for _, row in tqdm(original_df.iterrows(), total=len(original_df), position=0, leave=True):
  judgement, headnote = row["judgement"], row["headnote"]
  prompt = f'{rubric_prompt}\n\nJudgement: {judgement}\n\nHeadnote: {headnote}'
  result = pipe(prompt, max_new_tokens=300)[0]['generated_text']
  append_to_csv(judgement, headnote, result, clean_response(headnote, result))

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

KeyboardInterrupt: